version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceOuterInnerResourcePlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceOuterInnerResourcePlugin.Integration.Test"
  schedule:
    interval: daily